export const ROOM_CONFIG = {
  minPlayers: 4,
  maxPlayers: 10,
  minCodeLength: 5,
  submissionSeconds: 35,
  votingSeconds: 20,
  scoreboardSeconds: 8,
  revealIntervalMs: 1800,
  customCharLimit: 120,
  cleanupIntervalMs: 30000,
  reconnectGraceMs: 120000,
  inactiveRoomMs: 10 * 60 * 1000
};

export const REACTION_SET = ["??", "??", "??", "??", "??", "??", "??", "??", "??", "LMAO"];

export const AVATAR_SET = ["??", "??", "??", "??", "??", "??", "??", "??", "??", "??", "??", "??"];

export const MEME_POOL = [
  { id: "m1", title: "Distracted Boyfriend", url: "https://i.imgflip.com/1ur9b0.jpg" },
  { id: "m2", title: "Drake Hotline Bling", url: "https://i.imgflip.com/30b1gx.jpg" },
  { id: "m3", title: "Two Buttons", url: "https://i.imgflip.com/1g8my4.jpg" },
  { id: "m4", title: "Change My Mind", url: "https://i.imgflip.com/24y43o.jpg" },
  { id: "m5", title: "Woman Yelling At Cat", url: "https://i.imgflip.com/345v97.jpg" },
  { id: "m6", title: "Expanding Brain", url: "https://i.imgflip.com/1jwhww.jpg" },
  { id: "m7", title: "Always Has Been", url: "https://i.imgflip.com/46e43q.png" },
  { id: "m8", title: "Gru's Plan", url: "https://i.imgflip.com/26jxvz.jpg" },
  { id: "m9", title: "Panik Kalm", url: "https://i.imgflip.com/2zo1ki.jpg" },
  { id: "m10", title: "Boardroom Meeting", url: "https://i.imgflip.com/m78d.jpg" },
  { id: "m11", title: "This Is Fine", url: "https://i.imgflip.com/wxica.jpg" },
  { id: "m12", title: "Buff Doge vs Cheems", url: "https://i.imgflip.com/43a45p.png" }
];

export const CAPTION_DECK = [
  "Me pretending I understood the assignment.",
  "POV: the Wi-Fi cut out during the boss fight.",
  "Me opening the fridge like new food spawned.",
  "This could have been an email.",
  "No thoughts, just vibes and poor decisions.",
  "I said what I said.",
  "Live footage of me faking confidence.",
  "Type \"real\" if this is literally you.",
  "Mentally I am in airplane mode.",
  "When the group chat goes from 0 to courtroom.",
  "I brought absolutely nothing to the table.",
  "Me acting surprised by consequences.",
  "Delulu but make it strategic.",
  "This is my villain origin PowerPoint.",
  "Silence. The cringe is loading.",
  "I fear I cooked and burned it anyway.",
  "Mood sponsored by sleep deprivation.",
  "You had to be there. I was there. Still confused.",
  "Bro is running on 2% battery and audacity.",
  "Respectfully, no.",
  "Me after one minor inconvenience:",
  "The intrusive thought had a great pitch deck.",
  "Free trial of competence has ended.",
  "Emotionally buffering...",
  "This meeting could have been violence.",
  "Task failed successfully.",
  "New achievement unlocked: public embarrassment.",
  "Me trying to gaslight the algorithm.",
  "This goes hard on mute.",
  "How did we get here.",
  "Born to slay, forced to reply-all.",
  "Me remembering I have responsibilities.",
  "Certified yikes moment.",
  "Me if overthinking was an Olympic event.",
  "Absolutely not, but continue.",
  "The timeline split right here.",
  "I can explain. I will not.",
  "This is between me and my browser history.",
  "Not me catching strays.",
  "Why is this lowkey my fault.",
  "Me trying to be normal for five minutes.",
  "Peak cinema.",
  "Proof that chaos is a team sport.",
  "I am once again asking for emotional support snacks.",
  "Straight up a side quest.",
  "The scream I scrumpt.",
  "He cooked, but nobody ate.",
  "I paid for the full keyboard and used caps lock.",
  "Me doing the bare minimum with maximum drama.",
  "It's giving unpaid intern energy.",
  "Hard launch of my flop era.",
  "Me forming a committee in my head.",
  "Can't relate, I was asleep.",
  "This belongs in a museum of poor choices.",
  "I fear the ratio is deserved.",
  "Me reading terms and conditions like bedtime stories.",
  "Friendship ended with logic.",
  "Pls clap.",
  "No context, just panic.",
  "Me opening 27 tabs to feel productive.",
  "I thought this was optional.",
  "That is above my emotional pay grade.",
  "The group project is now a social experiment.",
  "Me speedrunning denial.",
  "Still not as bad as Monday.",
  "Absolutely legendary fumble.",
  "I fear this ate.",
  "It's giving final boss cutscene.",
  "NPC behavior honestly.",
  "My lawyer advised me not to answer.",
  "Me trying to out-meme destiny.",
  "New lore just dropped.",
  "This is why aliens do not visit.",
  "Just built different (incorrectly).",
  "A rare W in the wild.",
  "I needed this like oxygen.",
  "The vibes are legally concerning.",
  "Big if true.",
  "The plot armor is insane.",
  "Taking this personally for no reason.",
  "Me sending \"haha\" while spiraling.",
  "Achievement unlocked: overcommitment.",
  "This is my emotional support bad idea.",
  "We listen and we do not judge.",
  "I can hear the clown music.",
  "For legal reasons, this is satire.",
  "Me clocking in to be unserious.",
  "Just another day on this cursed timeline.",
  "I saw nothing. I know everything.",
  "Chat, is this real.",
  "Me and who?",
  "The confidence was unearned but inspiring.",
  "Built on caffeine and lies.",
  "Lowkey a masterpiece.",
  "Delete this before my mom sees.",
  "I support women's rights and wrongs.",
  "This was not in the tutorial.",
  "Me acting normal in front of company.",
  "This image has sound and it's screaming.",
  "Mood: raccoon with a ring light.",
  "Me pretending I won't send this to the group chat."
];